name: r-dynamic-coloring
services:
  model:
    build: ./model
    image: ${REGISTRY_URL}/coloring-service:${TAG:-latest}
    ports:
      - 8000:8000
    volumes:
      - ./model:/app
    networks:
      default:

  api:
    build: ./api
    image: ${REGISTRY_URL}/coloring-api:${TAG:-latest}
    ports:
      - 8080:8080
    environment:
      - COLORING_MICROSERVICE_URL=${COLORING_MICROSERVICE_URL}
      - DATABASE_HOST=database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=postgres
      - DATABASE_PORT=5432
    
    depends_on:
      - database
    networks:
      default:

  agent:
    build: ./agent
    image: ${REGISTRY_URL}/coloring-agent:${TAG:-latest}
    ports:
      - 8001:8000
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    
    depends_on:
      - database
    networks:
      default:

  database:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      default:
    
networks:
  default:
    name: coloring-network
    driver: bridge