version: '3.8'
name: r-dynamic-coloring
services:

  agent:
    build: ./agent
    ports:
      - 8001:8000
    environment:
    - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    - LANGSMITH_PROJECT=graph-analysis-agent
    - LANGSMITH_TRACING=false
    - HOST=0.0.0.0
    - PORT=8000
    - VISUALIZATION_DIR=./visualizations
    - SOURCES_DIR=./sources


  model:
    build: ./model
    ports:
      - 8000:8000
    volumes:
      - ./model:/app

  api:
    build: ./api
    ports:
      - 8080:8080
    environment:
      - COLORING_MICROSERVICE_URL=model
      - AGENT_MICROSERVICE_URL=agent
      - DATABASE_HOST=database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=postgres
      - DATABASE_PORT=5432
    
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    