name: grids
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py312hbdd6827_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.16=h5eee18b_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.1=pyhc872135_2
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py312hee96239_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.12.9=h5148396_0
  - pyzmq=27.1.0=py312hcf8288c_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.5.1=py312h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - click==8.3.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dnspython==2.8.0
      - email-validator==2.3.0
      - fastapi==0.119.0
      - fastapi-cli==0.0.13
      - fastapi-cloud-cli==0.3.1
      - fonttools==4.58.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - idna==3.10
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - networkx==3.4.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - pulp==3.1.1
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.0
      - sentry-sdk==2.41.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.48.0
      - tqdm==4.67.1
      - typer==0.19.2
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websockets==15.0.1
