environment_variables:
  - AUTH_TRUST_HOST
  - AUTH_SECRET
  - NEXT_PUBLIC_STACK_PROJECT_ID
  - NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY
  - STACK_SECRET_SERVER_KEY
  - NEXT_PUBLIC_R_HUED_COLORING_API
