environment_variables:
  - DOCKER_LOGIN_USER
  - DOCKER_LOGIN_TOKEN
  - RENDER_API_KEY
  - RENDER_WEB_SERVICE_ID_AGENT
  - RENDER_WEB_SERVICE_ID_API
  - RENDER_WEB_SERVICE_ID_MODEL
  - VERCEL_ORG_ID
  - VERCEL_PROJECT_ID
  - VERCEL_TOKEN
