environment_variables:
  - COLORING_MICROSERVICE_URL
  - AGENT_MICROSERVICE_URL
  - DATABASE_HOST
  - DATABASE_USER
  - DATABASE_PASSWORD
  - DATABASE_DBNAME
  - DATABASE_PORT
  - C_MODEL_API_KEY
  - C_AGENT_API_KEY
